#!/bin/sh

set -e

PACKAGE="gites-website"
PACKAGE_HOME="/home/gdw/$PACKAGE"

export CLIENT_HOME="$PACKAGE_HOME/var/instance01"
$PACKAGE_HOME/bin/gdw_db_migration upgrade head

case "$1" in
    configure)
	# create var
	/bin/chown -R gdw.gdw $PACKAGE_HOME

    ;;

    abort-remove|abort-upgrade|abort-deconfigure)
        echo "abort"
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
