#!/bin/sh

set -e

PACKAGE="gites-website"
PACKAGE_HOME="/home/gdw/$PACKAGE"

case "$1" in
    configure)
	# create var
	/bin/mkdir -p $PACKAGE_HOME/var/blobstorage
	/bin/mkdir -p $PACKAGE_HOME/var/filestorage
	/bin/mkdir -p $PACKAGE_HOME/var/instance
	/bin/mkdir -p $PACKAGE_HOME/var/log
	/bin/chown -R gdw.gdw $PACKAGE_HOME
	/bin/chmod 0700 $PACKAGE_HOME/var/blobstorage
	/bin/chmod 0700 $PACKAGE_HOME/var/filestorage

    ;;

    abort-remove|abort-upgrade|abort-deconfigure)
        echo "abort"
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
